### ISSUE TITLE
[Bug] Simplified: No difference between Functional Only and All

### ISSUE THREAD

**Issue by NiklasBr** [ConnectHolland/cookie-consent-bundle#64]
When using the simpliofied version of the consent it is impossible to distinguish between *Accept all* and *Accept functional only* options.

The cookies becomes:

 Accept-all
```
 Cookie_Consent_Key: 5ef9ce9d9cd6d
 Cookie_Consent: [datetime]
```

  Functional only
```
  Cookie_Consent_Key: 5ef9cef75a920
  Cookie_Consent: [datetime]
```

Configuration:
```yml
ch_cookie_consent:
    theme: dark
    categories: ~
    use_logger: false
    position: 'top'
    simplified: true
```

This means that `chcookieconsent_isCookieConsentSavedByUser()` no longer works.
